// This file was autogenerated for Supabase integration. If you migrate off Supabase,
// replace usages with your own API client. Leaving a guard to avoid accidental calls.

const USING_SUPABASE = false; // Set true only if Supabase is configured

if (USING_SUPABASE) {
  // eslint-disable-next-line no-console
  console.warn('[Supabase] Client file is still referenced. Consider migrating to backend API client.');
}

export const supabase: any = new Proxy({}, {
  get() {
    throw new Error('Supabase client is disabled. Update the code to use your backend API instead.');
  }
});